version: "3.7"

services:
  dynamodb:
    image: "amazon/dynamodb-local:1.22.0"
    command: "-jar DynamoDBLocal.jar -dbPath ./data -sharedDb"
    working_dir: /home/dynamodblocal
    ports:
      - 4579:8000
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    user: root

volumes:
  dynamodb-data:
