# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Set up test infra
      run: docker run -p 4579:8000 amazon/dynamodb-local:1.22.0 -jar DynamoDBLocal.jar -sharedDb &

    - name: Wait test infra
      run: sleep 10

    - name: Test
      run: go test -v ./... -integration
